# Generated by Django 5.0.4 on 2024-04-17 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=255)),
                ('rezyser', models.CharField(max_length=100)),
                ('opis', models.TextField()),
                ('poczatek_emisji', models.IntegerField()),
                ('koniec_emisji', models.IntegerField(blank=True, null=True)),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seriale', to='filmy.kategoria')),
            ],
        ),
    ]
