# Generated by Django 5.0.4 on 2024-04-17 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0004_remove_film_kategoria_remove_serial_kategoria_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='film',
            unique_together={('tytul', 'rezyser', 'rok_wydania')},
        ),
        migrations.AlterUniqueTogether(
            name='serial',
            unique_together={('tytul', 'poczatek_emisji')},
        ),
    ]
