# Generated by Django 5.0.4 on 2024-04-24 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0006_alter_ocena_ocena_alter_ocenaserial_ocena_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocenaserial',
            name='serial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocena', to='filmy.serial'),
        ),
    ]
