# Generated by Django 5.0.4 on 2024-04-24 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmy', '0007_alter_ocenaserial_serial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocenaserial',
            name='serial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oceny', to='filmy.serial'),
        ),
    ]
